version: 0.0
os: linux
files:
  - source: /build
    destination: /var/www/html/
    overwrite: true
    
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after.sh
      timeout: 300
      runas: root
